/**
 * P5-06 step C — TS reducers for the `trackEdit` ops (the track-row write path).
 *
 * These are verified by the GOLDEN HARNESS (`trackOpsGolden.test.ts` against
 * `web/fixtures/track-ops.json`, generated by `TrackOpGoldenTests.swift` driving the REAL Swift
 * dispatch). They are NOT written from the schema comments — three of those were wrong, and a
 * reducer written from them is wrong on day one:
 *
 *   setGain   the engine has NO CLAMP at all (the comment's 0…2 is the UI range)
 *   setVolume the engine clamps 0…3, not 0…2
 *   setToneQ  the engine clamps 0.5…18, not 0.7…16
 *
 * DELIBERATELY NOT MODELED (they stay Swift, and the reasons are structural, not laziness):
 *
 *   setStepCount · cyclePlaybackMode  — both keep HIDDEN RESTORE BUFFERS off the wire
 *       (setStepCount stashes the removed tail and restores it on grow; cyclePlaybackMode
 *       flattens cellLengths on entering OWN and restores them on leaving). A reducer cannot
 *       reproduce them without the buffers, and the buffers are not published.
 *   toggleDirection · toggleLocatorRepeat · setOutputAssign · setTuning
 *       — SELECTION-SCOPED: they mutate every selected track, and the selection is native.
 *   loadSample · browseSample · loadInstrument · clearInstrument · openInstrumentEditor ·
 *   setInstrumentOut · setMidiInputPin · toggleLaunch · mapMod
 *       — IMPURE: NSOpenPanel, the SampleBank, the AU host, the audio clock, or a read-back.
 *   renameTrack · setMidiChannel · setMidiVelocity · toggleSolo · setActiveCellParameter
 *       — they write fields that are not on the pattern wire, so they are invisible to it.
 */
import type { GridTrackState } from "../../protocol/schema";
import { deriveTrackState } from "./deriveTrackState";
import { CHORD_COUNT } from "./chordLibrary";

export interface TrackOp {
  op: string;
  value?: number;
  index?: number;
  mode?: string;
  startStep?: number; // setLocatorRange window start
  engage?: boolean; // setLocatorRange: also engage locator repeat
}

/** Ops whose effect these reducers fully model — the rest poison the shadow chain. */
export const VERIFIABLE_TRACK_OPS = new Set([
  "setGain", "setVolume", "setPan", "setTone", "setToneFilterMode", "setToneQ", "setFilterDrive",
  "setPitch", "setFineTune", "setChokeGroup", "setVoiceMode", "setStereoMode",
  "setSend", "setGlidePercent", "setSwing", "toggleMute", "setPatternStart",
  "setPreSilence", "setFreeRate", "stepSpeed", "resetSpeed", "setSpeedMultiplier", "setRateLockRatio",
  "setPlaybackDirection", "setSpeedMode", "cycleSubMode", "setStretchTimeOnly",
  "setSampleStart", "setSampleEnd", "setLoopStart", "setLoopEnd", "setLoopCrossfade",
  "setDefaultChop", "setChopPoint", "resetChopPoint", "setChopCount",
  "setOwnerAttack", "setOwnerGate", "setMelodicPitchMode", "setSampleOut",
  "setMidiOutEnabled", "setMidiRootNote", "setMidiGate",
  "adjustLocatorStart", "adjustLocatorLength", "clearCellParameter",
  // DJ perform gestures. Modeled here since DECKPLUGIN v2 §1 — see the reducers.
  "setLocatorRange", "setLocatorRepeat",
  // C3b — modeled WITH their own restore buffers (see TrackBuffers).
  "setStepCount", "cyclePlaybackMode",
]);

/**
 * Ops the desktop app owns via SETTINGS scenes, not the grid pattern. Swift deliberately does
 * NOT read these from the whole-pattern payload it adopts (WebWorldBinding.applyTrackScalars),
 * so publishing the pattern in owner mode is not enough — the value must also be sent as its own
 * `trackEdit` command. In the browser companion (no Swift) the publish IS the write, so both
 * paths are correct. Keep these in VERIFIABLE_TRACK_OPS too (the reducer still models them).
 */
export const SETTINGS_OWNED_TRACK_OPS = new Set(["setChokeGroup"]);

/**
 * Ops the owner path applies and publishes WITHOUT recording an undo entry.
 *
 * The locator mutators are undo-free live-perf ops throughout — the donor's `setLocatorRange`
 * and `setLocatorRepeatActive` register none, and GridPanel's PERF release already sends them
 * outside any undo bracket. Now that they are modeled (DECKPLUGIN v2 §1) they reach
 * `publishOwned`, which records by default — so one PERF drag would push an entry and ⌘Z would
 * walk the performance instead of the edits.
 *
 * ⚠️ The DELTA steppers (`adjustLocatorStart`/`adjustLocatorLength`, the row's ⌊ ⌉ boxes) are
 * deliberately NOT here: they are discrete row edits and have recorded undo since P5-06.
 */
export const UNDO_FREE_TRACK_OPS = new Set(["setLocatorRange", "setLocatorRepeat"]);

/**
 * Ops that fan out across a multi-track selection (NAV-12).
 *
 * This is exactly the set native already fans out through its
 * `updateMultipleTracks*` family — the web was the last surface still editing
 * one track while several were tinted. It is deliberately NOT "every track op":
 *
 *  - `setGain` is absent because native has no `updateMultipleTracksGain`.
 *  - The sample window (start/end/chop) is absent because those are positions
 *    inside a PARTICULAR sample; the same millisecond means nothing on the next
 *    track's audio. (Native does fan these from its own trim bar, where the drag
 *    is on a waveform — the row's boxes are not that gesture.)
 *  - Per-cell / topology ops are absent: they already fan out Swift-side behind
 *    `keepWithinSelection`, and doing it twice would double-apply.
 *
 * A fan-out op is UNMODELED by the reducers below on purpose: they model ONE
 * track, and the fan-out touches tracks this per-track chain does not see. Swift
 * does the work and pushes the result (GridPanel.sendTrackEditRaw).
 */
export const SELECTION_FANOUT_OPS = new Set([
  "setVolume", "setPan", "setPitch", "setTone", "setToneFilterMode",
  "setToneQ", "setFilterDrive", "setSend", "setStereoMode",
  // No web control sends `setFineTune` yet — the pitch box only moves whole
  // semitones, while native's pitch drag emits semitones AND cents together
  // (ContentView:5600). Listed so a fine-tune control fans out the day it lands;
  // Swift's handler already routes it (applySelectionFanOut).
  "setFineTune",
]);

/**
 * Does this edit move the whole selection, or just the track it landed on?
 *
 * Three clauses, each load-bearing:
 *  - the op is one native fans out (above);
 *  - MORE than one track is selected — with one, `effectiveSelectedTrackIds` is
 *    that track anyway, so a "fan-out" would be a no-op detour down the
 *    unmodeled path, throwing away the owner-mode reducer for nothing;
 *  - the touched track is IN the set — editing a track outside the selection is
 *    an ordinary edit, never a surprise mass-edit (Finder's rule, the same one
 *    `keepWithinSelection` follows).
 *
 * `selected` is Swift's `effectiveSelectedTrackIds` as pushed in the grid meta —
 * the same list the tint paints, so what MOVES is exactly what LOOKS selected.
 */
export function fansOutToSelection(
  op: string,
  trackIndex: unknown,
  selected: readonly number[],
): boolean {
  return (
    SELECTION_FANOUT_OPS.has(op) &&
    typeof trackIndex === "number" &&
    selected.length > 1 &&
    selected.includes(trackIndex)
  );
}

const clamp = (v: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, v));
const f32 = (v: number) => Math.fround(v); // engine stores most of these as Float

/** SpeedRatioTiming.ratioTable — Track.swift:119-127, 17 entries ascending. */
const RATIO_TABLE = [
  0.25, 1 / 3, 0.5, 2 / 3, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 4.0, 6.0, 8.0, 12.0, 16.0,
];

/** Nearest detent within `tol`, or null. Mirrors Track.normalizedAllowedRatio. */
function allowedRatio(mult: number, tol: number): number | null {
  for (const r of RATIO_TABLE) if (Math.abs(r - mult) < tol) return r;
  return null;
}

/**
 * clampLoopParameters — BeatSequencer.swift:13075. Runs after setLoopStart/End/Crossfade,
 * setSampleStart/End and setLoopEnabled(true). Re-fits the loop inside the sample window.
 */
function clampLoop(t: GridTrackState): GridTrackState {
  const eStart = Math.max(0, t.sampleStartMs);
  const rawEnd =
    t.sampleEndMs > eStart ? t.sampleEndMs : t.sampleDurationMs > 0 ? t.sampleDurationMs : eStart + 1;
  const trimEnd = Math.max(eStart + 1, rawEnd);

  let loopEndMs = t.loopEndMs;
  let loopStartMs = t.loopStartMs;
  if (loopEndMs <= eStart) loopEndMs = trimEnd;
  if (loopStartMs < eStart || loopStartMs >= loopEndMs) {
    loopStartMs = Math.min(Math.max(eStart, loopStartMs), loopEndMs - 1);
  }
  loopEndMs = Math.max(loopStartMs + 1, Math.min(loopEndMs, trimEnd));
  const loopCrossfadeMs = clamp(t.loopCrossfadeMs, 0, Math.max(0, loopEndMs - loopStartMs - 1));
  return { ...t, loopStartMs, loopEndMs, loopCrossfadeMs };
}

/** activeChopCount — BeatSequencer.swift:12928. */
const activeChopCount = (t: GridTrackState) => clamp(t.chopCount, 1, 8);

/** clampChopSelections — BeatSequencer.swift:12932. */
function clampChopSelections(t: GridTrackState): GridTrackState {
  const n = activeChopCount(t);
  return {
    ...t,
    defaultChopIndex: t.defaultChopIndex >= 0 ? Math.min(t.defaultChopIndex, n - 1) : t.defaultChopIndex,
    cellChopIndices: t.cellChopIndices.map((c) => (c < 0 ? -1 : Math.min(c, n - 1))),
  };
}

/**
 * The sub-mode ⊕. The exclusion is enforced by the MUTATORS, not the caller
 * (BeatSequencer.swift:12695 / :12708 / :12969) — which is why these are three helpers and not
 * three field writes.
 *
 * NOTE the wire carries the DERIVED loop/stretch flags: for a REG or OWN track (the only two
 * modes the consolidated model uses) `loopEnabled` on the wire equals the raw flag, and
 * `stretchToCell` equals `stretchEnabled` in REG. That is what makes these modelable at all.
 */
function setLoopEnabled(t: GridTrackState, on: boolean): GridTrackState {
  let next = { ...t, loopEnabled: on };
  if (on) {
    next = { ...next, defaultChopIndex: -1, stretchToCell: false };
    next = clampLoop(next);
  }
  return next;
}
function setStretchEnabled(t: GridTrackState, on: boolean): GridTrackState {
  const next = { ...t, stretchToCell: on };
  return on ? { ...next, loopEnabled: false } : next;
}
function setDefaultChopIndex(t: GridTrackState, idx: number): GridTrackState {
  const clamped = clamp(idx, -1, activeChopCount(t) - 1);
  const next = { ...t, defaultChopIndex: clamped };
  return clamped >= 0 ? { ...next, loopEnabled: false } : next;
}

/** clearPerCellParameter — BeatSequencer.swift:12193. Also NORMALIZES the array to stepCount. */
function clearCellParameter(t: GridTrackState, mode: string): GridTrackState {
  const n = t.stepCount;
  const fill = <T,>(v: T): T[] => Array(n).fill(v) as T[];
  switch (mode) {
    case "pitch":
    case "midiNote":
      return { ...t, pitchOffsets: fill(0) }; // same array — deliberate
    case "sampleStart":
      return { ...t, sampleStartMsOffsets: fill(0) };
    case "sampleEnd":
      return { ...t, sampleEndMsOffsets: fill(0) };
    // ⚠️ CROSSED, and deliberately so (BeatSequencer.swift:12202). `volume` clears the
    // POST-clipper array and `gain` clears the PRE-clipper one. The single easiest bug here.
    case "volume":
      return { ...t, mixVolumeOffsets: fill(0) };
    case "gain":
      return { ...t, volumeOffsets: fill(0) };
    case "pan":
      return { ...t, panOffsets: fill(0) };
    case "tone":
      return { ...t, toneOffsets: fill(0) };
    case "reverse":
      return { ...t, reverseSteps: fill(false) };
    case "rhythmicOffset":
      return { ...t, rhythmicOffsetRatios: fill(0) };
    case "preSilence":
      return { ...t, preSilenceMsOffsets: fill(0) };
    case "chop":
      return { ...t, cellChopIndices: fill(-1) };
    case "flam":
      return { ...t, flamCounts: fill(1) };
    case "glide":
      return { ...t, glideSteps: fill(false) };
    case "accent":
      return { ...t, accentLevels: fill(0) };
    case "chord":
      return { ...t, chordIndices: fill(0) };
    case "cellLength":
      // ⚠️ ALSO nulls the wrap — a wrapped cell whose length is cleared has no owner left.
      return { ...t, cellLengths: fill(1), wrapSourceStep: null };
    case "midiVelocity":
      // Fills from the track-default `midiVelocity` scalar, which is NOT on the wire.
      // Unmodelable — fall through to a no-op and let it poison the chain.
      return t;
    default:
      return t; // stereoMode is an explicit no-op in Swift too
  }
}

/** Max flam/ratchet count (kMaxFlam) — matches cellAffordances.fanCount's 1…16. */
const MAX_FLAM = 16;

/** Return a copy of `arr` grown to at least `len`, padding with `fill`. Swift's
 *  adjustStepParameter extends the per-step arrays on demand (a cell can extend
 *  past the pattern length, so `step` may exceed the current array). */
function grown<T>(arr: readonly T[], len: number, fill: T): T[] {
  if (arr.length >= len) return arr.slice();
  return [...arr, ...Array(len - arr.length).fill(fill)];
}

/** clampedToneValue — the offset case's absolute clamp (BeatSequencer.swift):
 *  bipolar ±100 in "tone" mode, |v| 0…100 in every filter mode. */
function clampTone(absolute: number, mode: string): number {
  return mode === "tone" ? clamp(absolute, -100, 100) : clamp(Math.abs(absolute), 0, 100);
}

/**
 * adjustStepParameter — BeatSequencer.swift:16528, the per-cell value edit
 * (vertical value-drag + ö/ä nudge). PORT because the browser companion has no
 * Swift to run it: on the desktop the `adjustParameter` intent reaches Swift,
 * but in the browser it was silently dropped, so per-cell pitch/tone/pan/… drag
 * did nothing. Applied through the owner write path (publishOwned) in the
 * browser only — the desktop keeps its Swift mutator (GridPanel.sendEdit).
 *
 * `step` is already the resolved OWNER/anchor target (resolveValueTargets did
 * the owner-mapping + validity gate), so this applies at `step` directly and
 * does NOT re-walk the extended-cell coverage the Swift version uses only to
 * accept/reject. `delta` is the raw notch delta; each parameter reproduces
 * Swift's own use of it — some scale by the full magnitude (pan/tone/volume/
 * sample trims: `delta * inc`), others act on its SIGN only (pitch/flam/accent/
 * chord/chop/cellLength/reverse/glide). `fine` = the ⌥ modifier (finer step).
 */
export function applyAdjustCellParameter(
  t: GridTrackState,
  step: number,
  delta: number,
  fine: boolean,
): GridTrackState {
  if (step < 0) return t;
  const dir = delta > 0 ? 1 : -1;

  switch (t.activeCellParameterName) {
    // pitch + midiNote share the pitchOffsets lane (quarter-tones; ⌥ = 0.1
    // semitone). Sign-only, clamped ±96 qt (±48 semitones).
    case "pitch":
    case "midiNote": {
      const pitchOffsets = grown(t.pitchOffsets, step + 1, 0);
      pitchOffsets[step] = clamp((pitchOffsets[step] ?? 0) + dir * (fine ? 0.2 : 2.0), -96, 96);
      return { ...t, pitchOffsets };
    }
    case "volume": {
      const mixVolumeOffsets = grown(t.mixVolumeOffsets, step + 1, 0);
      const absolute = clamp(t.volume + (mixVolumeOffsets[step] ?? 0) + delta * 0.05, 0, 2);
      mixVolumeOffsets[step] = f32(absolute - t.volume);
      return { ...t, mixVolumeOffsets };
    }
    case "gain": {
      const volumeOffsets = grown(t.volumeOffsets, step + 1, 0);
      const absolute = clamp(t.gain + (volumeOffsets[step] ?? 0) + delta * 0.01, 0, 2);
      volumeOffsets[step] = f32(absolute - t.gain);
      return { ...t, volumeOffsets };
    }
    case "pan": {
      const panOffsets = grown(t.panOffsets, step + 1, 0);
      const absolute = clamp(t.pan + (panOffsets[step] ?? 0) + delta * 0.1, -1, 1);
      panOffsets[step] = f32(absolute - t.pan);
      return { ...t, panOffsets };
    }
    case "tone": {
      const toneOffsets = grown(t.toneOffsets, step + 1, 0);
      const absolute = clampTone(t.tone + (toneOffsets[step] ?? 0) + delta * 2.0, t.toneFilterMode);
      toneOffsets[step] = f32(absolute - t.tone);
      return { ...t, toneOffsets };
    }
    case "sampleStart": {
      const sampleStartMsOffsets = grown(t.sampleStartMsOffsets, step + 1, 0);
      const maxDur = t.sampleDurationMs > 0 ? t.sampleDurationMs : t.sampleEndMs;
      const absolute = clamp(t.sampleStartMs + (sampleStartMsOffsets[step] ?? 0) + delta * 5.0, -1000, maxDur - 1);
      sampleStartMsOffsets[step] = absolute - t.sampleStartMs;
      // Mutual exclusion: a manual start edit clears the cell's chop assignment.
      const cellChopIndices = grown(t.cellChopIndices, step + 1, -1);
      cellChopIndices[step] = -1;
      return { ...t, sampleStartMsOffsets, cellChopIndices };
    }
    case "sampleEnd": {
      const sampleEndMsOffsets = grown(t.sampleEndMsOffsets, step + 1, 0);
      const absolute = clamp(
        t.sampleEndMs + (sampleEndMsOffsets[step] ?? 0) + delta * 5.0,
        t.sampleStartMs + 1,
        t.sampleDurationMs,
      );
      sampleEndMsOffsets[step] = absolute - t.sampleEndMs;
      return { ...t, sampleEndMsOffsets };
    }
    case "preSilence": {
      const preSilenceMsOffsets = grown(t.preSilenceMsOffsets, step + 1, 0);
      const absolute = clamp(t.preSilenceMs + (preSilenceMsOffsets[step] ?? 0) + delta * 5.0, 0, 1000);
      preSilenceMsOffsets[step] = absolute - t.preSilenceMs;
      return { ...t, preSilenceMsOffsets };
    }
    case "midiVelocity": {
      const midiVelocities = grown(t.midiVelocities, step + 1, t.midiVelocities[0] ?? 100);
      const cur = t.midiVelocities[step] ?? t.midiVelocities[0] ?? 100;
      midiVelocities[step] = clamp(cur + dir * (fine ? 1 : 5), 0, 127);
      return { ...t, midiVelocities };
    }
    case "cellLength": {
      const cellLengths = grown(t.cellLengths, step + 1, 1);
      const maxLength = Math.max(1, t.stepCount - step);
      cellLengths[step] = clamp((cellLengths[step] || 1) + dir, 1, maxLength);
      return { ...t, cellLengths };
    }
    case "reverse": {
      const reverseSteps = grown(t.reverseSteps, step + 1, false);
      reverseSteps[step] = delta > 0;
      return { ...t, reverseSteps };
    }
    case "glide": {
      const glideSteps = grown(t.glideSteps, step + 1, false);
      glideSteps[step] = delta > 0;
      return { ...t, glideSteps };
    }
    case "flam": {
      const flamCounts = grown(t.flamCounts, step + 1, 1);
      const cur = (flamCounts[step] ?? 1) < 1 ? 1 : (flamCounts[step] ?? 1);
      flamCounts[step] = clamp(cur + dir, 1, MAX_FLAM);
      return { ...t, flamCounts };
    }
    case "accent": {
      const accentLevels = grown(t.accentLevels, step + 1, 0);
      accentLevels[step] = ((accentLevels[step] ?? 0) + dir + 3) % 3;
      return { ...t, accentLevels };
    }
    case "chop": {
      const cellChopIndices = grown(t.cellChopIndices, step + 1, -1);
      const total = activeChopCount(t) + 1; // + the "off/default" slot (−1)
      const mapped = (cellChopIndices[step] ?? -1) + 1;
      cellChopIndices[step] = ((mapped + dir + total) % total) - 1;
      return { ...t, cellChopIndices };
    }
    case "chord": {
      const chordIndices = grown(t.chordIndices, step + 1, 0);
      const cur = clamp(chordIndices[step] ?? 0, 0, CHORD_COUNT - 1);
      chordIndices[step] = clamp(cur + dir, 0, CHORD_COUNT - 1);
      return { ...t, chordIndices };
    }
    // stereoMode / rhythmicOffset / sends have no web dial surface; a no-op
    // matches Swift's default for an unreachable lane.
    default:
      return t;
  }
}

/**
 * THE HIDDEN RESTORE BUFFERS (C3b).
 *
 * `setStepCount` and `cyclePlaybackMode` are not pure functions of the wire — they read and
 * write private stashes. Shrink a pattern 16→8 and grow back, and the steps you had in 9–16
 * come BACK; that non-destructive resize is a feature, and the stash is how. Entering OWN
 * flattens every multi-step cell to length 1 and remembers the originals; leaving OWN restores
 * them, and with them the extension steps' pitch/volume/pan/tone/reverse values.
 *
 * TS is NOT trying to mirror Swift's buffers — it cannot, and after the flip it will not need
 * to: it owns the document and keeps its OWN stash, starting empty from a loaded session.
 * That is exactly the state a golden fixture starts in, which is why these are verifiable there
 * and unverifiable in the shadow store (which joins mid-session, buffers unknown).
 *
 * The stash rides ALONGSIDE the wire fields and is invisible to `projectPattern`, so it can
 * never leak into a comparison or a push.
 */
export interface TrackBuffers {
  storedSteps: boolean[];
  storedPitchOffsets: number[];
  storedAccentLevels: number[];
  storedCellLengths: number[];
  /** step → the length it had before a shrink clamped it. */
  clampedCellLengths: Record<number, number>;
  /** step → the length it had before OWN flattened it. */
  storedOwnerModeCellLengths: Record<number, number>;
  /** extension step → its value before OWN made it an independent cell. */
  ext: {
    pitchOffsets: Record<number, number>;
    volumeOffsets: Record<number, number>;
    mixVolumeOffsets: Record<number, number>;
    panOffsets: Record<number, number>;
    sampleStartMsOffsets: Record<number, number>;
    sampleEndMsOffsets: Record<number, number>;
    toneOffsets: Record<number, number>;
    reverseSteps: Record<number, boolean>;
  };
}

export type TrackWithBuffers = GridTrackState & { buffers?: TrackBuffers };

export const emptyBuffers = (): TrackBuffers => ({
  storedSteps: [],
  storedPitchOffsets: [],
  storedAccentLevels: [],
  storedCellLengths: [],
  clampedCellLengths: {},
  storedOwnerModeCellLengths: {},
  ext: {
    pitchOffsets: {},
    volumeOffsets: {},
    mixVolumeOffsets: {},
    panOffsets: {},
    sampleStartMsOffsets: {},
    sampleEndMsOffsets: {},
    toneOffsets: {},
    reverseSteps: {},
  },
});

const buffersOf = (t: TrackWithBuffers): TrackBuffers => t.buffers ?? emptyBuffers();

/** updateStepCount — BeatSequencer.swift:5005. Ported branch for branch. */
function setStepCount(t0: GridTrackState, stepCount: number): GridTrackState {
  const t = t0 as TrackWithBuffers;
  const b = structuredClone(buffersOf(t));
  const current = t.steps.length;
  if (stepCount === current) return t0; // updateStepCountsForSelection SKIPS an unchanged track

  let steps = [...t.steps];
  let pitchOffsets = [...t.pitchOffsets];
  let accentLevels = [...t.accentLevels];
  let cellLengths = [...t.cellLengths];

  if (stepCount < current) {
    const extras = current - stepCount;
    // Pad cellLengths to steps BEFORE anything else (Swift does this first).
    while (cellLengths.length < steps.length) cellLengths.push(1);

    // Clamp cells that would now overhang the end, remembering their ORIGINAL length. This runs
    // over the whole current range — a cell can START before the new end and reach past it.
    for (let i = 0; i < Math.min(cellLengths.length, current); i++) {
      const len = cellLengths[i]!;
      if (len > 1 && i + len > stepCount) {
        if (b.clampedCellLengths[i] === undefined) b.clampedCellLengths[i] = len;
        cellLengths[i] = Math.max(1, stepCount - i);
      }
    }
    // Stash the removed tails — PREPENDED, so the most recent shrink restores first.
    if (cellLengths.length >= stepCount + extras) {
      b.storedCellLengths.unshift(...cellLengths.slice(cellLengths.length - extras));
    }
    b.storedSteps.unshift(...steps.slice(steps.length - extras));
    b.storedPitchOffsets.unshift(...pitchOffsets.slice(pitchOffsets.length - extras));
    b.storedAccentLevels.unshift(...accentLevels.slice(accentLevels.length - extras));

    steps = steps.slice(0, stepCount);
    pitchOffsets = pitchOffsets.slice(0, stepCount);
    accentLevels = accentLevels.slice(0, stepCount);
    if (cellLengths.length > stepCount) cellLengths = cellLengths.slice(0, stepCount);
  } else {
    const diff = stepCount - current;
    const restoreCount = Math.min(diff, b.storedSteps.length);

    if (restoreCount > 0) {
      steps.push(...b.storedSteps.slice(0, restoreCount));
      pitchOffsets.push(...b.storedPitchOffsets.slice(0, restoreCount));
      accentLevels.push(...b.storedAccentLevels.slice(0, restoreCount));

      const restoreLens = Math.min(restoreCount, b.storedCellLengths.length);
      if (restoreLens > 0) {
        cellLengths.push(...b.storedCellLengths.slice(0, restoreLens));
        b.storedCellLengths = b.storedCellLengths.slice(restoreLens);
      }
      if (restoreLens < restoreCount) {
        cellLengths.push(...Array(restoreCount - restoreLens).fill(1));
      }
      b.storedSteps = b.storedSteps.slice(restoreCount);
      b.storedPitchOffsets = b.storedPitchOffsets.slice(restoreCount);
      b.storedAccentLevels = b.storedAccentLevels.slice(restoreCount);
    }
    if (diff > restoreCount) {
      const rest = diff - restoreCount;
      steps.push(...Array(rest).fill(false));
      pitchOffsets.push(...Array(rest).fill(0));
      accentLevels.push(...Array(rest).fill(0));
      cellLengths.push(...Array(rest).fill(1));
    }
    while (cellLengths.length < stepCount) cellLengths.push(1);

    // Give the clamped cells back as much length as the new pattern allows — fully (and forget
    // them) when it fits, partially otherwise (and keep remembering).
    for (const key of Object.keys(b.clampedCellLengths)) {
      const i = Number(key);
      const original = b.clampedCellLengths[i]!;
      if (i < 0 || i >= cellLengths.length) continue;
      const maxPossible = stepCount - i;
      if (maxPossible >= original) {
        cellLengths[i] = original;
        delete b.clampedCellLengths[i];
      } else if (maxPossible > cellLengths[i]!) {
        cellLengths[i] = maxPossible;
      }
    }
  }

  // Tail (always): the locator re-fits to the new pattern, reading the RAW end.
  const locN = Math.max(1, steps.length);
  const locStart = clamp(t.locatorStartStep, 0, locN - 1);
  const locLen = Math.max(1, Math.min(locN, t.locatorEndStep - locStart + 1));

  const next = deriveTrackState({
    ...t,
    steps,
    pitchOffsets,
    accentLevels,
    cellLengths,
    stepCount: steps.length,
    locatorStartStep: locStart,
    locatorEndStep: locStart + locLen - 1,
  });
  return { ...next, buffers: b } as GridTrackState;
}

/**
 * cyclePlaybackMode — the handler flips OWN ⇄ REG (WebGridBinding), and
 * `updateTrackPlaybackMode` (BeatSequencer.swift:9862) does the store/restore.
 */
function cyclePlaybackMode(t0: GridTrackState): GridTrackState {
  const t = t0 as TrackWithBuffers;
  const b = structuredClone(buffersOf(t));
  const toOwner = t.playbackMode !== "owner";

  const cellLengths = [...t.cellLengths];
  const pitchOffsets = [...t.pitchOffsets];
  const volumeOffsets = [...t.volumeOffsets];
  const mixVolumeOffsets = [...t.mixVolumeOffsets];
  const panOffsets = [...t.panOffsets];
  const sampleStartMsOffsets = [...t.sampleStartMsOffsets];
  const sampleEndMsOffsets = [...t.sampleEndMsOffsets];
  const toneOffsets = [...t.toneOffsets];
  const reverseSteps = [...t.reverseSteps];

  if (toOwner) {
    // Entering OWN: there are no extensions here, so every multi-step cell FLATTENS to 1 — and
    // its extension steps become independent cells. Remember what they were, or leaving OWN
    // could not put the pattern back.
    const fresh = emptyBuffers();
    b.storedOwnerModeCellLengths = fresh.storedOwnerModeCellLengths;
    b.ext = fresh.ext;

    for (let owner = 0; owner < t.steps.length; owner++) {
      if (!t.steps[owner]) continue;
      const len = cellLengths[owner] ?? 1;
      if (len > 1) {
        b.storedOwnerModeCellLengths[owner] = len;
        if (cellLengths.length > owner) cellLengths[owner] = 1;
      }
      for (let off = 1; off < len; off++) {
        const ext = owner + off;
        if (ext >= t.steps.length) break;
        if (ext < pitchOffsets.length) b.ext.pitchOffsets[ext] = pitchOffsets[ext]!;
        if (ext < volumeOffsets.length) b.ext.volumeOffsets[ext] = volumeOffsets[ext]!;
        if (ext < mixVolumeOffsets.length) b.ext.mixVolumeOffsets[ext] = mixVolumeOffsets[ext]!;
        if (ext < panOffsets.length) b.ext.panOffsets[ext] = panOffsets[ext]!;
        if (ext < sampleStartMsOffsets.length) b.ext.sampleStartMsOffsets[ext] = sampleStartMsOffsets[ext]!;
        if (ext < sampleEndMsOffsets.length) b.ext.sampleEndMsOffsets[ext] = sampleEndMsOffsets[ext]!;
        if (ext < toneOffsets.length) b.ext.toneOffsets[ext] = toneOffsets[ext]!;
        if (ext < reverseSteps.length) b.ext.reverseSteps[ext] = reverseSteps[ext]!;
      }
    }
  } else {
    // Leaving OWN: put the lengths back (only where the owner cell still EXISTS — delete it in
    // OWN and it does not come back), then the extension steps' values, then forget the stash.
    for (const key of Object.keys(b.storedOwnerModeCellLengths)) {
      const i = Number(key);
      if (i < t.steps.length && t.steps[i]) {
        while (cellLengths.length <= i) cellLengths.push(1);
        cellLengths[i] = b.storedOwnerModeCellLengths[i]!;
      }
    }
    const put = <T,>(store: Record<number, T>, arr: T[]) => {
      for (const key of Object.keys(store)) {
        const i = Number(key);
        if (i < arr.length) arr[i] = store[i]!;
      }
    };
    put(b.ext.pitchOffsets, pitchOffsets);
    put(b.ext.volumeOffsets, volumeOffsets);
    put(b.ext.mixVolumeOffsets, mixVolumeOffsets);
    put(b.ext.panOffsets, panOffsets);
    put(b.ext.sampleStartMsOffsets, sampleStartMsOffsets);
    put(b.ext.sampleEndMsOffsets, sampleEndMsOffsets);
    put(b.ext.toneOffsets, toneOffsets);
    put(b.ext.reverseSteps, reverseSteps);

    const fresh = emptyBuffers();
    b.storedOwnerModeCellLengths = fresh.storedOwnerModeCellLengths;
    b.ext = fresh.ext;
  }

  const next = deriveTrackState({
    ...t,
    playbackMode: toOwner ? "owner" : "regular",
    cellLengths,
    pitchOffsets,
    volumeOffsets,
    mixVolumeOffsets,
    panOffsets,
    sampleStartMsOffsets,
    sampleEndMsOffsets,
    toneOffsets,
    reverseSteps,
  });
  return { ...next, buffers: b } as GridTrackState;
}

export function applyTrackOp(t: GridTrackState, op: TrackOp): GridTrackState {
  const v = op.value ?? 0;
  const n = Math.max(1, t.stepCount);

  switch (op.op) {
    // --- simple scalars (clamps taken from the MUTATORS, not the comments)
    case "setGain":
      return deriveTrackState({ ...t, gain: f32(v) }); // NO clamp — the engine has none
    case "setVolume":
      return { ...t, volume: f32(clamp(v, 0, 3)) }; // 0…3, not 0…2
    case "setPan":
      return { ...t, pan: f32(clamp(v, -1, 1)) };
    case "setToneQ":
      return { ...t, toneQ: f32(clamp(v, 0.5, 18)) }; // 0.5…18, not 0.7…16
    case "setFilterDrive":
      return { ...t, filterDrive: f32(clamp(v, 0, 100)) };
    case "setPitch":
      return { ...t, globalPitchOffset: clamp(Math.round(v), -96, 96) }; // quarter-tones
    case "setFineTune":
      return { ...t, globalFineTuneCents: clamp(Math.round(v), -50, 50) };
    case "setChokeGroup":
      return { ...t, chokeGroup: clamp(Math.round(v), 0, 8) };
    case "setSwing":
      return { ...t, swing: clamp(v / 100, 0, 1) }; // the HANDLER divides by 100
    case "setGlidePercent":
      return { ...t, glidePercent: clamp(v, 0, 100) };
    case "setPreSilence":
      return { ...t, preSilenceMs: clamp(v, 0, 1000) };
    case "setOwnerAttack":
      return { ...t, ownerAttack: f32(clamp(v, 0, 100)) };
    case "setOwnerGate":
      // 0…100, NOT 1…100 — a FOURTH wire comment that misstated the engine (BeatSequencer:12827).
      // The golden harness caught this on its first run; I had written the comment's range.
      return { ...t, ownerGate: f32(clamp(v, 0, 100)) };
    case "setMidiGate":
      return { ...t, midiGatePercent: clamp(v, 1, 100) };
    case "setMidiRootNote":
      return { ...t, midiRootNote: Math.min(127, Math.max(0, Math.round(v))) };
    case "setPatternStart": {
      const s = clamp(Math.round(v), 0, n - 1);
      return { ...t, patternStartStep: s === 0 ? null : s }; // 0 encodes as null on the wire
    }
    case "toggleMute":
      return { ...t, muted: !t.muted }; // solo does NOT interact
    case "setVoiceMode":
      return op.mode === "mono" || op.mode === "poly" ? { ...t, voiceMode: op.mode } : t;
    case "setStereoMode":
      return { ...t, stereoMode: clamp(Math.round(v), 0, 3) };
    case "setMelodicPitchMode":
      return { ...t, melodicPitchMode: v !== 0 };
    case "setMidiOutEnabled":
      return { ...t, midiOutEnabled: v !== 0 };
    case "setSampleOut":
      // Writes trackType, NOT a boolean field of its own.
      return { ...t, trackType: v !== 0 ? "audio" : "midi" };
    case "setPlaybackDirection":
      return { ...t, playbackDirectionReversed: v !== 0 };

    case "setSend": {
      const level = f32(clamp(v, 0, 1));
      switch (op.index) {
        case 1: return { ...t, send1Level: level };
        case 2: return { ...t, send2Level: level };
        case 3: return { ...t, send3Level: level };
        case 4: return { ...t, send4Level: level };
        default: return t;
      }
    }

    // --- tone: the sign fold (clampedToneValue / convertedToneValue)
    case "setTone": {
      const bipolar = t.toneFilterMode === "tone";
      return {
        ...t,
        tone: f32(bipolar ? clamp(v, -100, 100) : clamp(Math.abs(v), 0, 100)),
      };
    }
    case "setToneFilterMode": {
      const to = op.mode;
      if (!to) return t;
      const from = t.toneFilterMode;
      const cur = t.tone;
      let tone: number;
      if (to === "tone") {
        // ⚠️ lowPass is the ONLY mode that maps back to a NEGATIVE tone.
        if (from === "lowPass") tone = -clamp(Math.abs(cur), 0, 100);
        else if (from === "tone") tone = clamp(cur, -100, 100);
        else tone = clamp(Math.abs(cur), 0, 100);
      } else {
        tone = clamp(Math.abs(cur), 0, 100); // every filter mode stores |v|
      }
      return { ...t, toneFilterMode: to, tone: f32(tone) };
    }

    // --- free rate: derived enable + neutral deadzone
    case "setFreeRate": {
      let r = clamp(v, -64, 64);
      if (Math.abs(r - 1.0) < 0.01) r = 1.0;
      return { ...t, freeRate: r, freeRateEnabled: r !== 1.0 };
    }

    // --- speed
    case "stepSpeed": {
      if (v === 0) return t;
      const cur = allowedRatio(t.speedMultiplier, 0.05) ?? 1.0;
      const i = RATIO_TABLE.indexOf(cur);
      const j = v > 0 ? Math.min(RATIO_TABLE.length - 1, i + 1) : Math.max(0, i - 1);
      return { ...t, speedMultiplier: RATIO_TABLE[j]! }; // clamps at both ends, no wrap
    }
    case "resetSpeed":
      return { ...t, speedMultiplier: 1.0 };
    case "setSpeedMultiplier": {
      const r = allowedRatio(v, 0.01);
      // ⚠️ NOT clamped: an off-table value is a SILENT NO-OP, not a snap.
      return r === null ? t : { ...t, speedMultiplier: r };
    }
    // Assign the per-track ⟳ reset target. Store-only — mirrors BeatSequencer.setRateLockRatio:
    // it does NOT touch speedMultiplier (the live rate). Off-table value = silent no-op.
    case "setRateLockRatio": {
      const r = allowedRatio(v, 0.01);
      return r === null ? t : { ...t, rateLockRatio: r };
    }
    case "setSpeedMode": {
      const m = Math.round(v);
      if (m !== 0 && m !== 1) return t; // timeStretch is rejected by the handler
      return { ...t, pitchSyncMode: m === 1, timeStretchMode: false };
    }
    case "setStretchTimeOnly":
      return { ...t, stretchTimeOnly: v !== 0 };

    // --- the sub-mode ⊕ cycle
    case "cycleSubMode": {
      const own = t.playbackMode === "owner";
      const cur = t.loopEnabled ? 2 : own ? (t.defaultChopIndex >= 0 ? 1 : 0) : t.stretchToCell ? 1 : 0;
      const next = (cur + 1) % 3;
      if (next === 2) return setLoopEnabled(t, true);
      if (next === 1) return own ? setDefaultChopIndex(t, 0) : setStretchEnabled(t, true);
      // → 0: turn BOTH off, in Swift's order
      return own
        ? setDefaultChopIndex(setLoopEnabled(t, false), -1)
        : setStretchEnabled(setLoopEnabled(t, false), false);
    }

    // --- chops
    case "setDefaultChop":
      return setDefaultChopIndex(t, Math.round(v));
    case "setChopCount": {
      const clamped = clamp(Math.round(v), 1, 8);
      if (clamped === activeChopCount(t)) return t; // guard: no-op if unchanged
      // ⚠️ A count change WIPES all 8 points and clamps every selection.
      return clampChopSelections({
        ...t,
        chopCount: clamped,
        chopPoints: Array(8).fill(-1),
      });
    }
    case "setChopPoint": {
      const i = op.index ?? -1;
      if (i < 0 || i >= activeChopCount(t)) return t;
      const maxDur = t.sampleDurationMs > 0 ? t.sampleDurationMs : Math.max(t.sampleEndMs, 1);
      const pts = [...t.chopPoints];
      while (pts.length < 8) pts.push(-1);
      pts[i] = clamp(v, 0, maxDur - 1);
      return { ...t, chopPoints: pts };
    }
    case "resetChopPoint": {
      const i = op.index ?? -1;
      if (i < 0 || i >= activeChopCount(t)) return t;
      const pts = [...t.chopPoints];
      while (pts.length < 8) pts.push(-1);
      pts[i] = -1;
      return { ...t, chopPoints: pts };
    }

    // --- sample window: moving the start/end REBASES every non-zero per-cell offset
    case "setSampleStart": {
      const maxDur = t.sampleDurationMs > 0 ? t.sampleDurationMs : t.sampleEndMs;
      const clamped = Math.max(-1000, Math.min(v, maxDur - 1));
      const diff = clamped - t.sampleStartMs;
      let offsets = t.sampleStartMsOffsets;
      if (diff !== 0) {
        const grown = [...offsets];
        while (grown.length < n) grown.push(0);
        offsets = grown.map((o) =>
          o !== 0 ? clamp(o - diff, -1000 - clamped, t.sampleEndMs - 1 - clamped) : o,
        );
      }
      return clampLoop({ ...t, sampleStartMs: clamped, sampleStartMsOffsets: offsets });
    }
    case "setSampleEnd": {
      const maxDur = t.sampleDurationMs > 0 ? t.sampleDurationMs : t.sampleEndMs;
      const minEnd = t.sampleStartMs + 1;
      const clamped = Math.max(minEnd, Math.min(v, maxDur));
      const diff = clamped - t.sampleEndMs;
      let offsets = t.sampleEndMsOffsets;
      if (diff !== 0) {
        const grown = [...offsets];
        while (grown.length < n) grown.push(0);
        const bound = maxDur - clamped;
        offsets = grown.map((o) => (o !== 0 ? clamp(o - diff, -bound, bound) : o));
      }
      return clampLoop({ ...t, sampleEndMs: clamped, sampleEndMsOffsets: offsets });
    }
    case "setLoopStart":
      return clampLoop({ ...t, loopStartMs: v });
    case "setLoopEnd":
      return clampLoop({ ...t, loopEndMs: v });
    case "setLoopCrossfade":
      return clampLoop({ ...t, loopCrossfadeMs: Math.max(0, v) });

    // --- locator. The document stores START + END, and the wire now carries both (C3b) — the
    // LENGTH is derived. It used to be the other way round, which lost the raw end (it may
    // exceed the pattern, encoding a wrap) and made setStepCount's re-fit unreproducible.
    case "adjustLocatorStart": {
      const delta = Math.round(v);
      if (delta === 0) return t;
      const len = t.locatorLengthSteps; // computed from the CURRENT start/end
      const start = (((t.locatorStartStep + delta) % n) + n) % n; // TRUE modulo — it wraps
      if (start === t.locatorStartStep) return t;
      return deriveTrackState({ ...t, locatorStartStep: start, locatorEndStep: start + len - 1 });
    }
    case "adjustLocatorLength": {
      const start = clamp(t.locatorStartStep, 0, n - 1); // also re-clamps the start
      const len = clamp(t.locatorLengthSteps + Math.round(v), 1, n);
      return deriveTrackState({ ...t, locatorStartStep: start, locatorEndStep: start + len - 1 });
    }

    // --- the DJ PERFORM gestures (absolute one-shots from the PERF locator drag), modeled since
    // DECKPLUGIN v2 §1. They used to be deliberately unmodeled on the reasoning "Swift owns the
    // engine's engagement latch, the web adopts the echo" — but there is no Swift in this tree.
    // `trackEdit` is not in `MergedLink.NATIVE_METHODS`, so both ops fell through to BrowserLink's
    // bare `return { ok: true }` and were SILENTLY DISCARDED: PERF previewed and committed nothing.
    //
    // The latch is safe to drive from a single publish. It lives entirely in the audio callback and
    // is a frame-to-frame RISING EDGE on `locatorRepeatActive` (`NativeAudioEngineCore.cpp:5409` —
    // `locatorWasActive` re-arms `locatorEngaged`), not a reaction to how many pushes arrived. One
    // world carrying the new window AND active=true is exactly the donor's range-then-engage order
    // with no window in between. Engaging when ALREADY engaged is a no-op in both (Swift's mutator
    // guards `!=`; no rising edge here either), so a re-drag moves the window without re-arming.
    case "setLocatorRange": {
      // Mirrors BeatSequencer.setLocatorRange: end is clamped INTO the pattern, so a drag can
      // never write the wrapping window that `locatorEndStep > stepCount-1` would encode.
      const len = Math.max(1, Math.round(v));
      const start = clamp(Math.round(op.startStep ?? t.locatorStartStep), 0, n - 1);
      const end = Math.max(start, Math.min(n - 1, start + len - 1));
      const repeat = op.engage ? true : t.locatorRepeatActive;
      return deriveTrackState({
        ...t,
        locatorStartStep: start,
        locatorEndStep: end,
        locatorRepeatActive: repeat,
      });
    }
    case "setLocatorRepeat":
      // ABSOLUTE per-track (unlike the selection-scoped `toggleLocatorRepeat`, which stays unmodeled).
      // Re-derives because `locatorStart`/`locatorLength` — the row's ⌊ ⌉ readouts — are null while off.
      return deriveTrackState({ ...t, locatorRepeatActive: v !== 0 });

    // --- THE TWO WITH HIDDEN BUFFERS (C3b). See `TrackBuffers` — TS keeps its OWN stash; it is
    // not trying to reproduce Swift's, which is why these are reducers and not a wire problem.
    case "setStepCount":
      return setStepCount(t, clamp(Math.round(v), 1, 64)); // the HANDLER clamps 1…64
    case "cyclePlaybackMode":
      return cyclePlaybackMode(t);

    case "clearCellParameter":
      return op.mode ? clearCellParameter(t, op.mode) : t;

    default:
      return t; // unmodeled — the caller poisons the chain
  }
}
