/**
 * WorldTrack field → engine param-NAME map — DERIVED from scoopy's worklet.
 *
 *   node --experimental-strip-types scripts/generateWorldMap.ts            (write)
 *   node --experimental-strip-types scripts/generateWorldMap.ts --check    (CI gate)
 *
 * WHY: scoopy's flat `World` (worldFromSession.ts) names each track field in
 * camelCase (`volume`, `toneMode`, `pitchOffsets`), while the engine knows them
 * as `SL_T_*` / `SL_TA_*`. The correspondence is scoopy's choice, not a
 * mechanical transform (`globalPitchOffset → SL_T_GLOBAL_PITCH`,
 * `send1Offsets → SL_TA_SEND1_OFFSETS`), and its authority is the worklet's own
 * SCALAR_FIELDS / ARRAY_FIELDS tables (scoopy-worklet.js) — the same tables it
 * uses to drive the WASM engine. The merged native shell sends the flat World
 * as-is and does this rename on its side, so the table is generated from the
 * pinned worklet rather than hand-mirrored (a mis-paired field writes a value
 * into the WRONG parameter — the exact hazard the worklet comment warns of).
 *
 * Emits `sl_worldmap.inc`: two {field, param} tables SlWorldApply walks. The
 * SL_T/SL_TA NAMES are resolved to ids at runtime through the ABI, so this file
 * never encodes an integer — a reorder in the engine cannot silently misalign.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const workletPath = resolve(appRoot, 'web/src/audio/scoopy-worklet.js')
const outPath = resolve(appRoot, 'slengine/generated/sl_worldmap.inc')

class GenerationRefused extends Error {}

/** Extract the [field, PARAM] pairs of a `const <name> = [ … ]` table. */
function pairs(source: string, tableName: string, paramPrefix: string): Array<[string, string]> {
  const start = source.indexOf(`const ${tableName} = [`)
  if (start < 0) throw new GenerationRefused(`no ${tableName} in ${workletPath}`)
  const end = source.indexOf('];', start)
  if (end < 0) throw new GenerationRefused(`${tableName} is not terminated`)
  const body = source.slice(start, end).replace(/\/\/[^\n]*/g, '')
  const out: Array<[string, string]> = []
  const seen = new Set<string>()
  for (const m of body.matchAll(/\[\s*"([A-Za-z0-9_]+)"\s*,\s*"(SL_T[A-Z_0-9]*)"\s*\]/g)) {
    const field = m[1]!, param = m[2]!
    if (!param.startsWith(paramPrefix))
      throw new GenerationRefused(`${tableName}: "${field}" maps to ${param}, not a ${paramPrefix}* name`)
    if (seen.has(field)) throw new GenerationRefused(`${tableName}: duplicate field "${field}"`)
    seen.add(field)
    out.push([field, param])
  }
  if (out.length === 0) throw new GenerationRefused(`${tableName} extracted empty`)
  return out
}

function table(name: string, rows: Array<[string, string]>): string {
  return [
    `static const struct { const char* field; const char* param; } ${name}[] = {`,
    ...rows.map(([f, p]) => `    {"${f}", "${p}"},`),
    `};`,
  ].join('\n')
}

function generate(): string {
  const source = readFileSync(workletPath, 'utf8')
  const scalar = pairs(source, 'SCALAR_FIELDS', 'SL_T_')
  const array = pairs(source, 'ARRAY_FIELDS', 'SL_TA_')

  const lockCommit = (() => {
    try {
      return JSON.parse(readFileSync(resolve(appRoot, 'engine.lock.json'), 'utf8')).sharedCommit as string
    } catch { return 'unknown' }
  })()

  return [
    `// GENERATED by web/scripts/generateWorldMap.ts — DO NOT EDIT.`,
    `//`,
    `// scoopy WorldTrack field -> engine param NAME, from the worklet's`,
    `// SCALAR_FIELDS / ARRAY_FIELDS (scoopy-worklet.js, vendored hash-pinned`,
    `// @ ${lockCommit.slice(0, 12)}). The names resolve to ids through the ABI at`,
    `// runtime, so no integer is encoded here. Regenerate: npm run worldmap:generate`,
    ``,
    table('kWorldScalarMap', scalar),
    ``,
    table('kWorldArrayMap', array),
    ``,
    `#define SL_WORLD_SCALAR_MAP_COUNT ${scalar.length}`,
    `#define SL_WORLD_ARRAY_MAP_COUNT ${array.length}`,
    ``,
  ].join('\n')
}

const check = process.argv.includes('--check')
try {
  const text = generate()
  if (check) {
    if (!existsSync(outPath) || readFileSync(outPath, 'utf8') !== text) {
      console.error('worldmap:check FAILED — the generated map is missing or stale.')
      console.error('scoopy\'s worklet field tables changed; run npm run worldmap:generate and review.')
      process.exit(1)
    }
    const n = (text.match(/\{"/g) ?? []).length
    console.log(`worldmap:check OK (${n} field mappings, in sync with the pinned worklet)`)
  } else {
    mkdirSync(dirname(outPath), { recursive: true })
    writeFileSync(outPath, text)
    console.log(`wrote ${outPath}`)
  }
} catch (e) {
  if (e instanceof GenerationRefused) {
    console.error('REFUSED to generate the world map:')
    console.error('  ' + e.message)
    process.exit(1)
  }
  throw e
}
