/**
 * SL HotFrame layout — DERIVED from scoopy's schema, never hand-counted.
 *
 *   node --experimental-strip-types scripts/generateHotFrame.ts            (write)
 *   node --experimental-strip-types scripts/generateHotFrame.ts --check    (CI gate)
 *
 * WHY: the HotFrame is scoopy's 30 Hz engine->UI telemetry — one flat
 * Float64Array whose every slot is addressed by POSITION on both sides. The
 * producer (this merged shell, native) and the consumer (scoopy's UI,
 * `HotFrameLayout` in schema.ts) MUST agree on every index, or a meter reads a
 * neighbour's value. Hand-transcribing 268 index constants is the exact
 * silent-corruption class the track-param generator exists to avoid, so the
 * layout is generated from the one authority: `HOT_FRAME_SCALARS` in scoopy's
 * `web/protocol/schema.ts`, vendored hash-pinned (engine.lock.json).
 *
 * HOW IT IS SAFE: every entry in HOT_FRAME_SCALARS is a plain string literal
 * (verified), so extraction is a comment-stripped read of the `"..."` tokens in
 * declaration order — the index IS the position. It refuses to emit on anything
 * unexpected (no array found, a duplicate name, a non-identifier name, a count
 * that disagrees with the pinned length constants) rather than write a layout
 * that looks finished and is off by one.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const schemaPath = resolve(appRoot, 'vendor/scoopy/web-protocol/schema.ts')
const outPath = resolve(appRoot, 'slengine/generated/sl_hotframe.inc')

class GenerationRefused extends Error {}

/** Strip // and /* *\/ comments so a quoted word inside a comment cannot be
    read as an array entry. */
function stripComments(s: string): string {
  return s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

function intConst(source: string, name: string): number {
  const m = source.match(new RegExp(`export const ${name}\\s*=\\s*(\\d+)`))
  if (!m) throw new GenerationRefused(`missing ${name} in ${schemaPath}`)
  return Number(m[1])
}

/** The string literals of HOT_FRAME_SCALARS, in declaration order. */
function scalars(source: string): string[] {
  const start = source.indexOf('HOT_FRAME_SCALARS = [')
  if (start < 0) throw new GenerationRefused(`no HOT_FRAME_SCALARS in ${schemaPath}`)
  const end = source.indexOf('] as const', start)
  if (end < 0) throw new GenerationRefused('HOT_FRAME_SCALARS is not terminated by `] as const`')
  const body = stripComments(source.slice(start + 'HOT_FRAME_SCALARS = ['.length, end))
  const names = [...body.matchAll(/"([^"]+)"/g)].map((m) => m[1]!)
  if (names.length === 0) throw new GenerationRefused('HOT_FRAME_SCALARS extracted empty')

  const seen = new Set<string>()
  for (const n of names) {
    if (!/^[A-Za-z_]\w*$/.test(n))
      throw new GenerationRefused(`"${n}" is not a valid C identifier — the emitter names it SL_HF_${n}`)
    if (seen.has(n)) throw new GenerationRefused(`duplicate HotFrame scalar "${n}"`)
    seen.add(n)
  }
  return names
}

function generate(): string {
  const source = readFileSync(schemaPath, 'utf8')
  const names = scalars(source)
  const spectrum = intConst(source, 'SPECTRUM_BIN_COUNT')

  // The pinned schema derives these; recomputing and cross-checking is how a
  // silent drift between the array and the length math is caught.
  const spectrumBase = names.length
  const length = spectrumBase + spectrum

  const lockCommit = (() => {
    try {
      return JSON.parse(readFileSync(resolve(appRoot, 'engine.lock.json'), 'utf8')).sharedCommit as string
    } catch { return 'unknown' }
  })()

  return [
    `// GENERATED by web/scripts/generateHotFrame.ts — DO NOT EDIT.`,
    `//`,
    `// The SL HotFrame layout, derived from scoopy's HOT_FRAME_SCALARS`,
    `// (web/protocol/schema.ts, vendored hash-pinned @ ${lockCommit.slice(0, 12)}). The producer`,
    `// (native) and consumer (scoopy UI) address this flat Float64 frame by`,
    `// position, so the indices MUST match the schema; that is why they are`,
    `// generated, not hand-counted.`,
    `//`,
    `// Regenerate: npm run hotframe:generate  ·  Verify: npm run hotframe:check`,
    ``,
    `enum {`,
    ...names.map((n, i) => `    SL_HF_${n} = ${i},`),
    `};`,
    ``,
    `// Scalars, then SPECTRUM_BIN_COUNT spectrum bins appended (HOT_FRAME_LENGTH).`,
    `#define SL_HOTFRAME_SCALAR_COUNT ${spectrumBase}`,
    `#define SL_HOTFRAME_SPECTRUM_BASE ${spectrumBase}`,
    `#define SL_HOTFRAME_SPECTRUM_COUNT ${spectrum}`,
    `#define SL_HOTFRAME_LENGTH ${length}`,
    ``,
  ].join('\n')
}

const check = process.argv.includes('--check')
try {
  const text = generate()
  if (check) {
    if (!existsSync(outPath)) {
      console.error(`hotframe:check FAILED — ${outPath} does not exist; run npm run hotframe:generate`)
      process.exit(1)
    }
    if (readFileSync(outPath, 'utf8') !== text) {
      console.error('hotframe:check FAILED — the generated layout is stale.')
      console.error('scoopy\'s HOT_FRAME_SCALARS changed; run npm run hotframe:generate and review the diff.')
      process.exit(1)
    }
    const len = text.match(/#define SL_HOTFRAME_LENGTH (\d+)/)?.[1]
    console.log(`hotframe:check OK (length ${len}, in sync with the pinned schema)`)
  } else {
    mkdirSync(dirname(outPath), { recursive: true })
    writeFileSync(outPath, text)
    console.log(`wrote ${outPath}`)
  }
} catch (e) {
  if (e instanceof GenerationRefused) {
    console.error('REFUSED to generate the HotFrame layout:')
    console.error('  ' + e.message)
    process.exit(1)
  }
  throw e
}
