// GENERATED by web/scripts/generateScratchTechniques.ts — DO NOT EDIT.
// Authority: slengine/scratch-techniques.json (its header carries the model).
// Regenerate: npm run scratch:generate   ·   Gate: npm run scratch:check

/** A scratch technique, as the UI needs it. THE INDEX IS THE WIRE: the engine's
 *  kSlScratchTechniques is emitted from the same authority in the same order, so
 *  `sl_tape_scratch_start` takes the position of an entry in this array. */
export interface ScratchTechnique {
  readonly id: string
  readonly label: string
  readonly hint: string
  readonly clickCount: number
  readonly clickWidthMs: number
  readonly strokeShape: 'sine' | 'asymmetric'
  /** Whether the fader RESTS open on the forward stroke — an open-fader
   *  technique is one whose direction change is heard. */
  readonly restOpen: boolean
  readonly span: number
  readonly periodBeats: number
}

export const SCRATCH_TECHNIQUES: readonly ScratchTechnique[] = [
  /** 0 — the reference case — pure record hand, every break is a phantom click */
  { id: 'baby', label: 'baby', hint: "the reference case — pure record hand, every break is a phantom click",
    clickCount: 0, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.06, periodBeats: 0.5 },
  /** 1 — a tremor, not a stroke — very fast, tiny span */
  { id: 'scribble', label: 'scribble', hint: "a tremor, not a stroke — very fast, tiny span",
    clickCount: 0, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.015, periodBeats: 0.125 },
  /** 2 — the cut — only the push sounds, the pull is silent */
  { id: 'forward', label: 'forward', hint: "the cut — only the push sounds, the pull is silent",
    clickCount: 0, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.08, periodBeats: 0.5 },
  /** 3 — a fast push at high pitch; the re-cue is not heard */
  { id: 'stab', label: 'stab', hint: "a fast push at high pitch; the re-cue is not heard",
    clickCount: 0, clickWidthMs: 40, strokeShape: 'asymmetric',
    restOpen: true, span: 0.12, periodBeats: 0.5 },
  /** 4 — closes directly after the gesture starts — one tone per stroke */
  { id: 'chirp', label: 'chirp', hint: "closes directly after the gesture starts — one tone per stroke",
    clickCount: 2, clickWidthMs: 55, strokeShape: 'sine',
    restOpen: false, span: 0.05, periodBeats: 0.5 },
  /** 5 — rest closed, several openings across the stroke — many tones per stroke */
  { id: 'transformer', label: 'transformer', hint: "rest closed, several openings across the stroke — many tones per stroke",
    clickCount: 4, clickWidthMs: 45, strokeShape: 'sine',
    restOpen: false, span: 0.07, periodBeats: 0.5 },
  /** 6 — one real click mid-stroke, plus its phantom — so it sounds like two */
  { id: 'flare1', label: 'flare · 1', hint: "one real click mid-stroke, plus its phantom — so it sounds like two",
    clickCount: 1, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.07, periodBeats: 0.5 },
  /** 7 — the canonical case: 2 real + 2 phantom, so it sounds like four */
  { id: 'flare2', label: 'flare · 2', hint: "the canonical case: 2 real + 2 phantom, so it sounds like four",
    clickCount: 2, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.07, periodBeats: 0.5 },
  /** 8 — four rapid clicks — thumb against four fingers; audio-wise a 4-click flare */
  { id: 'crab', label: 'crab', hint: "four rapid clicks — thumb against four fingers; audio-wise a 4-click flare",
    clickCount: 4, clickWidthMs: 30, strokeShape: 'sine',
    restOpen: true, span: 0.07, periodBeats: 0.5 },
  /** 9 — a flare that continues on BOTH strokes rather than one */
  { id: 'orbit', label: 'orbit', hint: "a flare that continues on BOTH strokes rather than one",
    clickCount: 2, clickWidthMs: 40, strokeShape: 'sine',
    restOpen: true, span: 0.07, periodBeats: 0.5 },
] as const
