#include "EmbeddedWeb.h"

#include "ScoopyPluginWebDist.h" // generated by juce_add_binary_data

namespace wizard::plugin {

EmbeddedWeb::EmbeddedWeb() {
    int size = 0;
    // ONE resource, whatever the web bundle's content hashes are this build —
    // and one archive for EVERY plugin, not one per product. There is a single
    // webdist in this repo; which face it shows is decided at runtime by the
    // `window.__slPanel` the editor injects, so the deck and the tape embed
    // identical bytes and share this target. See the ⚠️ in ../CMakeLists.txt.
    const char* data = ScoopyPluginWebDist::getNamedResource("webdist_zip", size);
    if (data == nullptr || size <= 0) return;
    stream = std::make_unique<juce::MemoryInputStream>(data, (size_t) size, false);
    zip = std::make_unique<juce::ZipFile>(stream.get(), false);
}

EmbeddedWeb& EmbeddedWeb::shared() {
    static EmbeddedWeb instance;
    return instance;
}

std::optional<wizard::webresources::Payload> EmbeddedWeb::load(const juce::String& path) const {
    if (zip == nullptr) return std::nullopt;

    const auto relative = wizard::webresources::normaliseRequestPath(path);
    if (!relative.has_value()) return std::nullopt;

    const int index = zip->getIndexOfFileName(*relative);
    if (index < 0) return std::nullopt;

    // createStreamForEntry returns null for a directory entry or a corrupt one.
    std::unique_ptr<juce::InputStream> entry(zip->createStreamForEntry(index));
    if (entry == nullptr) return std::nullopt;

    wizard::webresources::Payload payload;
    payload.data.reset();
    {
        juce::MemoryOutputStream out(payload.data, false);
        out.writeFromInputStream(*entry, -1);
    }
    payload.mimeType = wizard::webresources::mimeForExtension(
        relative->fromLastOccurrenceOf(".", false, false).toLowerCase());
    return payload;
}

} // namespace wizard::plugin
